/**
 * 接口配置
 * 用于管理需要自动添加标段ID的接口列表
 */

// 需要自动添加标段ID的接口URL列表
export const APIs_NEED_SECTION_ID = [
  "/v1/supervisionReport",
  "/v1/supervisionLogManagement",
  "/v1/supervisionReportManagement",
  "/v1/supervisionFormReply",
  "/v1/supervisionNotice",
  "/v1/supervisionDetailManagement",
  "/v1/checkRectification",
  "/v1/reportResult",
  "/v1/policyManagement",
  "/v1/targetManagement",
  "/v1/emergencyManagement",
  "/v1/internalTrainingRecord",
  "/v1/safetyDrillTrainingRecordManagement",
  "/v1/lnternalTrainingProgram",
  "/v1/hazardInspection",
  "/v1/hazardManagement",
  "/v1/securityPlan",
  "/v1/securityChecklist",
  "/v1/specialPersonnelManagement",
  "/v1/projectDivision",
  "/v1/unitProject",
  "/v1/parallelReport",
  "/v1/parallelCheckOne",
  "/v1/parallelCheckTwo",
  "/v1/parallelCheckThree",
  "/v1/parallelCheckFour",
  "/v1/parallelCheckFive",
  "/v1/parallelCheckSix",
  "/v1/parallelCheckSeven",
  "/v1/parallelCheckEight",
  "/v1/parallelCheckNine",
  "/v1/parallelCheckTen",
  "/v1/parallelCheckEleven",
  "/v1/parallelCheckTwelve",
  "/v1/parallelCheckThirteen",
  "/v1/certificateManagement",
  "/v1/changeManagement",
  "/v1/changeInstruction",
  "/v1/changePriceReview",
  "/v1/defaultManagement",
  "/v1/meetingMinutesManual",
  "/v1/meetingMinutesUploadFile",
  "/v1/photos",
  "/v1/inspectionChecklist",
  "/v1/inspectionChecklistManagement",
  "/v1/projectFileRelation",
  "/v1/management",
  "/v1/archiveFile",
  "/v1/archiveFile/category",
];

// 不能自动加项目ID的接口
export const APIs_NO_NEED_PROJECT_ID = [
  "/capA2: A208",
  "/dictionary/item/codes",
  "/dictionary/item/ids",
  "/dictionary/{dictionaryCode}/dictionaryItem",
  "/file",
  "/file/download",
  "/file/download/{fileId}",
  "/file/fileIds",
  "/file/preview/{fileId}",
  "/file/upload",
  "/file/upload1",
  "/file/{fileId}",
  "/log",
  "/log/{logId}",
  "/log/{logId}/retry",
  "/menu",
  "/menu/permission",
  "/menu/permission/function",
  "/menu/tree",
  "/menu/{id}/role",
  "/menu/{menuId}",
  "/menu/{menuId}/group",
  "/menu/{menuId}/operation",
  "/menu/{roleId}/role",
  "/organization",
  "/organization/tree",
  "/organization/{organId}",
  "/organization/{organizationId}/role",
  "/preview/{imageId}",
  "/role",
  "/role/{id}",
  "/role/{roleId}/organization",
  "/role/{roleId}/user",
  "/user",
  "/user/password",
  "/user/register",
  "/user/reset/{userId}",
  "/user/token",
  "/user/{id}",
  "/user/{userId}/role",
  "/v1/apiInbound/{ids}",
  "/v1/apiOutbound/{ids}",

  "/v1/apiToken",
  "/v1/apiToken/batch/add",
  "/v1/apiToken/batch/delete",
  "/v1/apiToken/delete/{ids}",
  "/v1/apiToken/find/one",
  "/v1/apiToken/{id}",

  "/v1/companyCheckPlan",
  "/v1/projectManagement",
  "/v1/todoList",
  "/v1/inspectionListDescription",
  "/v1/regulationCategory",
  "/v1/rulesRegulation",
];
